# Generated by Django 4.2 on 2025-10-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                ("documento", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("codigo_ingreso", models.AutoField(primary_key=True, serialize=False)),
                ("direccion", models.CharField(max_length=150)),
                ("telefono", models.CharField(max_length=20)),
            ],
        ),
    ]
