# Generated by Django 4.2 on 2025-10-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
