# Generated by Django 4.2 on 2025-10-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("laboratoristas", "0001_initial"),
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("colesterol_total", models.FloatField()),
                ("colesterol_hdl", models.FloatField()),
                ("colesterol_ldl", models.FloatField()),
                ("trigliceridos", models.FloatField()),
                (
                    "laboratorista",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laboratoristas.laboratorista",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes.paciente",
                    ),
                ),
            ],
        ),
    ]
