# Generated by Django 4.2 on 2025-10-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laboratorista",
            fields=[
                (
                    "codigo_interno",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("titulo", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
            ],
        ),
    ]
